# Generated by Django 5.2.8 on 2026-01-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(choices=[('Mid Term', 'Mid Term'), ('Test Exam', 'Test Exam'), ('Final Exam', 'Final Exam')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Class_name',
            field=models.CharField(choices=[('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 7', 'Class 7'), ('Class 10', 'Class 10'), ('Class 6', 'Class 6')], max_length=50),
        ),
    ]
